### ISSUE TITLE
Abnormal screen brightness

### ISSUE THREAD

**Issue by FreeLife2** [TIMISONG-dev/kernel_xiaomi_sm8250#3]
On Apollo models, when displaying certain app options with floating windows, the screen brightness flickers, repeatedly dims, and then brightens. Please note that it is not a FOD fingerprint

**Comment by TIMISONG-dev** [comment]
AOSP or MIUI?

**Comment by FreeLife2** [comment]
aosp

**Comment by TIMISONG-dev** [comment]
Fix soon

**Comment by TIMISONG-dev** [comment]
Fixed? I revert some display changes

**Comment by FreeLife2** [comment]
I will verify it within 24 hours. Previously, this bug appeared 100% in the app pop-up window

**Comment by FreeLife2** [comment]
Verified, the problem still exists, and other kernels do not have this bug. Confirmed to be a kernel bug

**Comment by FreeLife2** [comment]
hot wire! I have identified the issue that caused the bug in the commit "disp: msm: sde: Only clear dim layers when necessary". After revoking this commit, the problem disappeared. After merging this commit again, the problem reoccurred. This commit will cause this serious bug. I will provide you with feedback and thank you for your work！

**Comment by TIMISONG-dev** [comment]
Ok, thx, I will revert

**Comment by TIMISONG-dev** [comment]
I revert the broken commit

**Comment by FreeLife2** [comment]
bug fixed
